id: A241D8C20
title: 'Self-Arising Wisdom: Songtsen Gampo Guru SÄdhana'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:38:46.014992
  last_modified_at: 2022-03-01 01:38:46.015000
